"use strict";

const bcrypt = require("bcrypt");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const usuarios = [
      {
        rut_usuario: "13308258-1",
        nombres: "Tatiana Andrea",
        apellidos: "Gutierrez Bunster",
        email: "tgutierr@ubiobio.cl",
        password: await bcrypt.hash("82581", 10),
        pin: 8258,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "tgutierr",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "14371917-0",
        nombres: "Alejandro Mauricio",
        apellidos: "Valdés Jimenez",
        email: "avaldes@ubiobio.cl",
        password: await bcrypt.hash("19170", 10),
        pin: 1917,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "avaldes",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "10399995-2",
        nombres: "Sergio Anibal",
        apellidos: "Araya Guzman",
        email: "saraya@ubiobio.cl",
        password: await bcrypt.hash("99952", 10),
        pin: 9995,
        horas_atrabajar: 44,
        id_rol: 1,
        id_cargo: 2,
        is_superuser: false,
        username: "saraya",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "14273436-2",
        nombres: "Alejanda Andrea",
        apellidos: "Segura Navarrete",
        email: "asegura@ubiobio.cl",
        password: await bcrypt.hash("34362", 10),
        pin: 3436,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "asegura",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "23735655-9",
        nombres: "Clemente",
        apellidos: "Rubio Manzano",
        email: "clrubio@ubiobio.cl",
        password: await bcrypt.hash("56559", 10),
        pin: 5655,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "clrubio",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "12609906-1",
        nombres: "Christian Lautaro",
        apellidos: "Vidal Castro",
        email: "cvidal@ubiobio.cl",
        password: await bcrypt.hash("99061", 10),
        pin: 9906,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "cvidal",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "12922969-1",
        nombres: "Mónica Alejandra",
        apellidos: "Caniupán Marileo",
        email: "mcaniupan@ubiobio.cl",
        password: await bcrypt.hash("29691", 10),
        pin: 2969,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "mcaniupan",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "10708974-8",
        nombres: "Karina Pilar",
        apellidos: "Rojas Contreras",
        email: "krojas@ubiobio.cl",
        password: await bcrypt.hash("89748", 10),
        pin: 8974,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "krojas",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "17343933-4",
        nombres: "Luis Emilio",
        apellidos: "Cabrera Crot",
        email: "lcabrera@ubiobio.cl",
        password: await bcrypt.hash("39334", 10),
        pin: 3933,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "lcabrera",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "16012431-8",
        nombres: "Rodrigo Ariel",
        apellidos: "Torres Avilés",
        email: "rtorres@ubiobio.cl",
        password: await bcrypt.hash("24318", 10),
        pin: 2431,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,
        is_superuser: false,
        username: "rtorres",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
      {
        rut_usuario: "8631998-5",
        nombres: "Juan Carlos",
        apellidos: "Parra Márquez",
        email: "jefecarrconce-icinf@ubiobio.cl",
        password: await bcrypt.hash("19985", 10),
        pin: 1998,
        horas_atrabajar: 44,
        id_rol: 2,
        id_cargo: 1,  
        is_superuser: false,
        username: "jparra",
        is_staff: false,
        is_active: true,
        date_joined: new Date(),
      },
    ];

    for (const usuario of usuarios) {
      try {
        await queryInterface.bulkInsert("Usuarios", [usuario], {
          ignoreDuplicates: true,
        });
      } catch (error) {
        // Error al insertar usuario, puedes agregar manejo aquí si es necesario
      }
    }
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Usuarios", null, {});
  },
};
