"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g-xo9*6zdqi0+39a!!*(kb$=$+d*bmt@grp1n4*b_h)#6z9c1q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['146.83.194.142', 'localhost', '127.0.0.1']

# Configuraciones CSRF para HTTP
CSRF_TRUSTED_ORIGINS = [
    'http://146.83.194.142',
    'http://146.83.194.142:1779',
    'http://146.83.194.142:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Configuraciones CSRF adicionales
CSRF_COOKIE_HTTPONLY = False  # Permitir acceso por JavaScript si es necesario
CSRF_USE_SESSIONS = False     # Usar cookies en lugar de sesiones
CSRF_COOKIE_SAMESITE = 'Lax'  # Política de cookies más permisiva


# Application definition

INSTALLED_APPS = [
    'modlector',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
]

MIDDLEWARE = [
    'modlector.middleware.FaviconMiddleware',
    'django.middleware.security.SecurityMiddleware',
   # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# Configuración de base de datos según el entorno
if DEBUG:  # DESARROLLO - Base de datos local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'RegistraUbb',
            'USER': 'postgres',
            'PASSWORD': 'holiwis',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }
    # URL del backend para desarrollo (puede ser localhost si tienes el backend corriendo local)
    BACKEND_URL = "http://127.0.0.1:3000/api/"  # Cambia el puerto según tu backend local
    
else:  # PRODUCCIÓN - Base de datos remota
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': 'andrea2025',
            'HOST': '146.83.194.142',
            'PORT': '1774',
        }
    }
    # URL del backend para producción
    BACKEND_URL = "http://146.83.194.142:1772/api/"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'modlector.Usuario'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Directorios adicionales de archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Usar storage estándar en desarrollo, comprimido en producción
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    #STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# CONFIGURACIONES DE SEGURIDAD PARA PRODUCCIÓN
# ==========================================

import os

ENABLE_BACKEND_SYNC = False

# Solo aplicar configuraciones de seguridad en producción
if not DEBUG:  # Cuando DEBUG=False (producción)
    
    # Configuraciones HTTP (sin SSL)
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # Cookies no seguras para HTTP
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    # Headers de seguridad básicos
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

    # Sin configuración de proxy SSL
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
    USE_TZ = True

    # Hosts permitidos
    ALLOWED_HOSTS = [ 
        '146.83.194.142',
        'localhost',
        '127.0.0.1',
    ]
    
    # Configuración mejorada de WhiteNoise para producción
    WHITENOISE_USE_FINDERS = False  # Desactivar en producción
    WHITENOISE_AUTOREFRESH = False  # Desactivar en producción
    
else:  # Desarrollo (DEBUG=True)
    
    # En desarrollo, permitir localhost
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        '0.0.0.0',
        '146.83.194.142',  # Agregar IP del servidor
    ]
    
    # Configuración de WhiteNoise para desarrollo
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

# ==========================================
# SECRET_KEY MEJORADA
# ==========================================

# Para producción, usa una SECRET_KEY generada específicamente
# Puedes generar una nueva en: https://djecrety.ir/
# O usar: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_secret_key())'

# En desarrollo mantienes la actual, en producción debes cambiarla
if not DEBUG:
    # ⚠️ CAMBIAR ESTA SECRET_KEY EN PRODUCCIÓN ⚠️
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'tu-secret-key-super-segura-de-al-menos-50-caracteres-aqui')