# Generated by Django 5.2.6 on 2025-09-11 00:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
                ('horas_trabajar', models.FloatField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id_justificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Justificacions',
            },
        ),
        migrations.CreateModel(
            name='Marcaje',
            fields=[
                ('id_marcaje', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Marcajes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Rols',
            },
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id_totem', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Totems',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asist', models.AutoField(primary_key=True, serialize=False)),
                ('colacion', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_justificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion')),
                ('id_marcaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.marcaje')),
            ],
            options={
                'db_table': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('periodo', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion')),
            ],
            options={
                'db_table': 'Motivos',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('aviso', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_asist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.asistencia')),
            ],
            options={
                'db_table': 'Notificacions',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut_usuario', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 o 12345678-K', regex='^[0-9]+-[0-9kK]{1}$')])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('horas_atrabajar', models.FloatField()),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.cargo')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.rol')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Registro_marcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_marcaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.marcaje')),
                ('id_totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.totem')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.usuario')),
            ],
            options={
                'db_table': 'RegistroMarcaje',
            },
        ),
        migrations.CreateModel(
            name='Registro_just',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.usuario')),
            ],
            options={
                'db_table': 'RegistroJust',
            },
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=100, unique=True)),
                ('estado_qr', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.usuario')),
            ],
            options={
                'db_table': 'Qrs',
            },
        ),
    ]
