# Generated by Django 4.2.24 on 2025-10-16 01:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut_usuario', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 o 12345678-K', regex='^[0-9]+-[0-9kK]{1}$')])),
                ('horas_atrabajar', models.FloatField()),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('intentos_pin', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asist', models.AutoField(primary_key=True, serialize=False)),
                ('colacion', models.BooleanField(default=False)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('horas_diarias', models.FloatField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Asistencia',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
                ('horas_trabajar', models.FloatField()),
            ],
            options={
                'db_table': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id_justificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Justificacions',
            },
        ),
        migrations.CreateModel(
            name='Marcaje',
            fields=[
                ('id_marcaje', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Marcajes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Rols',
            },
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id_totem', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Totems',
            },
        ),
        migrations.CreateModel(
            name='Registro_marcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_marcaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.marcaje')),
                ('id_totem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.totem')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RegistroMarcaje',
            },
        ),
        migrations.CreateModel(
            name='Registro_just',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RegistroJust',
            },
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=100, unique=True)),
                ('estado_qr', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Qrs',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('aviso', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_asist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.asistencia')),
            ],
            options={
                'db_table': 'Notificacions',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('periodo', models.TimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('id_justificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion')),
            ],
            options={
                'db_table': 'Motivos',
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_justificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_marcaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modlector.marcaje'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modlector.cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modlector.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
