# Generated by Django 4.2.24 on 2025-10-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='horas_atrabajar',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
