# Generated by Django 4.2.24 on 2025-11-16 01:51

from django.db import migrations, models
import modlector.models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='createdAt',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='fecha_registro',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='createdAt',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
        migrations.AlterField(
            model_name='qr',
            name='fecha_creacion',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
        migrations.AlterField(
            model_name='registro_marcaje',
            name='fecha_registro',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
        migrations.AlterField(
            model_name='rol',
            name='createdAt',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
        migrations.AlterField(
            model_name='totem',
            name='createdAt',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
    ]
