# Generated by Django 4.2.24 on 2025-11-08 23:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcaje',
            name='id_totem',
        ),
        migrations.RemoveField(
            model_name='marcaje',
            name='rut_usuario',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='registro_just',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
        ),
        migrations.AlterField(
            model_name='registro_marcaje',
            name='rut_usuario',
            field=models.CharField(db_column='rut_usuario', max_length=30, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 o 12345678-K', regex='^[0-9]+-[0-9kK]{1}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_usuario',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 o 12345678-K', regex='^[0-9]+-[0-9kK]{1}$')]),
        ),
    ]
