# Generated by Django 4.2.24 on 2025-11-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0002_remove_marcaje_id_totem_remove_marcaje_rut_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcaje',
            name='id_totem',
            field=models.ForeignKey(db_column='id_totem', default=1, on_delete=django.db.models.deletion.CASCADE, to='modlector.totem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marcaje',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
            preserve_default=False,
        ),
    ]
