# Generated by Django 4.2.24 on 2025-10-16 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0002_alter_usuario_horas_atrabajar_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_cargo',
            field=models.ForeignKey(db_column='id_cargo', null=True, on_delete=django.db.models.deletion.CASCADE, to='modlector.cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', null=True, on_delete=django.db.models.deletion.CASCADE, to='modlector.rol'),
        ),
    ]
