# Generated by Django 4.2.24 on 2025-11-16 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0002_alter_asistencia_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcaje',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
