# Generated by Django 4.2.24 on 2025-10-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0003_alter_usuario_id_cargo_alter_usuario_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='intentos_pin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
