# Generated by Django 4.2.24 on 2025-11-16 04:04

from django.db import migrations, models
import modlector.models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0003_alter_marcaje_createdat_alter_marcaje_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcaje',
            name='createdAt',
            field=models.DateTimeField(default=modlector.models.get_current_chile_time),
        ),
        migrations.AlterField(
            model_name='marcaje',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
