# Generated by Django 4.2.24 on 2025-10-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0004_alter_usuario_intentos_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, db_column='nombres', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, db_column='apellidos', max_length=150),
        ),
    ]
