# Generated by Django 4.2.24 on 2025-10-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0005_alter_usuario_first_name_alter_usuario_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qr',
            table='QRs',
        ),
    ]
