# Generated by Django 4.2.24 on 2025-10-16 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0006_alter_qr_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
        ),
        migrations.AlterField(
            model_name='registro_just',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
        ),
        migrations.AlterField(
            model_name='registro_marcaje',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
        ),
    ]
