# Generated by Django 4.2.24 on 2025-10-16 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0007_alter_qr_rut_usuario_alter_registro_just_rut_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='id_justificacion',
            field=models.ForeignKey(blank=True, db_column='id_justificacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='id_marcaje',
            field=models.ForeignKey(db_column='id_marcaje', on_delete=django.db.models.deletion.CASCADE, to='modlector.marcaje'),
        ),
        migrations.AlterField(
            model_name='motivo',
            name='id_justificacion',
            field=models.ForeignKey(db_column='id_justificacion', on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id_asist',
            field=models.ForeignKey(db_column='id_asist', on_delete=django.db.models.deletion.CASCADE, to='modlector.asistencia'),
        ),
        migrations.AlterField(
            model_name='qr',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro_just',
            name='id_justificacion',
            field=models.ForeignKey(db_column='id_justificacion', on_delete=django.db.models.deletion.CASCADE, to='modlector.justificacion'),
        ),
        migrations.AlterField(
            model_name='registro_just',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro_marcaje',
            name='id_marcaje',
            field=models.ForeignKey(db_column='id_marcaje', on_delete=django.db.models.deletion.CASCADE, to='modlector.marcaje'),
        ),
        migrations.AlterField(
            model_name='registro_marcaje',
            name='id_totem',
            field=models.ForeignKey(db_column='id_totem', on_delete=django.db.models.deletion.CASCADE, to='modlector.totem'),
        ),
        migrations.AlterField(
            model_name='registro_marcaje',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
