# Generated by Django 4.2.24 on 2025-10-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0008_alter_asistencia_id_justificacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='justificacion',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='justificacion',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='marcaje',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='marcaje',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='motivo',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='motivo',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='qr',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='qr',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='totem',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='totem',
            old_name='updatedat',
            new_name='updatedAt',
        ),
    ]
