# Generated by Django 4.2.24 on 2025-10-16 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0009_rename_createdat_asistencia_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
        ),
    ]
