# Generated by Django 4.2.24 on 2025-10-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0010_alter_qr_rut_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='codigo_unico',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
