# Generated by Django 4.2.24 on 2025-11-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0011_alter_qr_codigo_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
