# Generated by Django 4.2.24 on 2025-11-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0012_usuario_foto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='updatedAt',
        ),
    ]
