# Generated by Django 4.2.24 on 2025-11-06 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0013_remove_qr_createdat_remove_qr_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_just',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
        ),
        migrations.AlterField(
            model_name='registro_marcaje',
            name='rut_usuario',
            field=models.ForeignKey(db_column='rut_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='rut_usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut_usuario',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 o 12345678-K', regex='^[0-9]+-[0-9kK]{1}$')]),
        ),
    ]
