# Generated by Django 4.2.24 on 2025-11-06 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modlector', '0014_alter_registro_just_rut_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_marcaje',
            name='rut_usuario',
            field=models.CharField(db_column='rut_usuario', max_length=30, validators=[django.core.validators.RegexValidator(message='El RUT debe tener el formato 12345678-9 o 12345678-K', regex='^[0-9]+-[0-9kK]{1}$')]),
        ),
    ]
